FROM --platform=linux/amd64 ubuntu:22.04

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential cmake git libpcre2-dev

RUN git clone https://github.com/CESNET/libyang
WORKDIR /libyang/build
RUN cmake ..
RUN make -j8
RUN make install

COPY . /repo
WORKDIR /repo/build
RUN cmake ..
RUN make -j8
